[package]
name = "actix-web-original-middleware-example"
version = "0.1.0"
authors = ["megumish <keishi.kawada@handii.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.7"
env_logger = "0.6.2"
